flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- MonadRandom-0.4.1
- StateVar-1.1.0.2
- adjunctions-4.2.2
- base-orphans-0.4.5
- bifunctors-5.1
- comonad-4.2.7.2
- contravariant-1.3.3
- distributive-0.4.4
- either-4.4.1
- exceptions-0.8.0.2
- free-4.12.1
- haskell-lexer-1.0
- kan-extensions-4.2.3
- lens-4.13
- mmorph-1.0.4
- monad-control-1.0.0.4
- prelude-extras-0.4.0.2
- pretty-show-1.6.9
- profunctors-5.1.2
- random-1.1
- reflection-2.1.1.1
- semigroupoids-5.0.0.4
- semigroups-0.18.0.1
- tagged-0.8.2
- transformers-base-0.4.4
- transformers-compat-0.4.0.4
- void-0.7.1
compiler-check: match-exact
compiler: ghcjs-0.1.0.20150924_ghc-7.10.2
resolver: ghcjs-0.1.0.20150924_ghc-7.10.2
